project:
  type: website
  output-dir: docs

website:
  title: "About me - Raphael Ngooi"
  favicon: Assets/favicon-16x16.png
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "My Resume"
        href: resume.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphael-ngooi-019aa8208/
      - icon: github
        href: https://github.com/Raphdraft1

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



